import Typography from "@mui/material/Typography";
import Container from "@mui/material/Container";
import Head from "next/head";

export default function Home() {
	return (
		<>
			<Head>
				<title>React Hook Form</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main>
				<Container maxWidth="md">
					<Typography align="center" variant="h2">
						React Hook Form
					</Typography>
				</Container>
			</main>
		</>
	);
}
