import { Character } from '@/interface'
import styles from '@/styles/Home.module.css'
import { GetStaticProps, NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'

interface Props{
  characters: Character[]
}

const Home:NextPage<Props> = ({characters}) => {

  return (
    <>
      <Head>
        <title>Ecommerce App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main}`}>
        <h1>Ecommerce App</h1>
        <div className={styles.grid}>
          {characters.map((character) => (
            <div key={character.tail}>
              <h3>{character.name}</h3>
              <Image src={character.image} alt={character.name} width={180} height={250} />
            </div>
            ))}
        </div>
      </main>
    </>
  )
}

export const getStaticProps: GetStaticProps = async () => {

  const character = await fetch('https://amiiboapi.com/api/amiibo/')
  const rest = await character.json()
  const data = rest.amiibo.slice(0, 20)

  
  return {
    props: {
      characters: data
    },
  }
}

export default Home
