import { Form } from "@/components/Form";
import Container from "@mui/material/Container";
import Typography from "@mui/material/Typography";
import Head from "next/head";

import { schema } from "@/rules";
import { yupResolver } from "@hookform/resolvers/yup";
import { FormProvider, useForm } from "react-hook-form";
import * as yup from "yup";

export default function Home() {
	type DataForm = yup.InferType<typeof schema>;

	const method = useForm<DataForm>({
		resolver: yupResolver(schema),
		defaultValues: {},
	});

	return (
		<>
			<Head>
				<title>React Hook Form</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main>
				<Container maxWidth="md">
					<Typography align="center" variant="h2">
						React Hook Form
					</Typography>
						<FormProvider {...method}>
						<Form />
					</FormProvider>
				</Container>
			</main>
		</>
	);
}
